cmd/ros-installer/main.go, docs/configuration.md, framework/files/etc/systemd/system/rancherd.service.d/override.conf, framework/files/etc/systemd/system/ros-installer.service.d/override.conf, framework/files/system/oem/01_ros-rootfs.yaml, tests/Makefile, tests/Vagrantfile, tests/assets/cloud_init.yaml, tests/smoke/smoke_test.go
This PR is multi-fold and contains several fixups I've found while digging cloud-init issues. The changes are split into separate commit for a better review. 
It introduces some logical changes, while until now all other changes were pretty cosmetical:
- ros-installer by default reading /oem/userdata for automated installation
- services have been reworked to wait on cos-setup-network rather network-online. This ensures userdata is loaded so installation configuration is picked up correctly
- cloud-init datasources logic changed slightly: in order to be sure that we pull the data from the network, we call explictly the userdata fetched if none was found previously. This impact only first-boot as subsequent boots have the userdata pulled correctly. I would suggest in the long term to …
=> Cloud init fixups

.github/workflows/integration-tests.yaml, Dockerfile, framework/files/etc/cos/bootargs.cfg, pkg/config/read.go, pkg/config/read_test.go
The following commit enables TPM emulation and its configuration in the
os2 configuration file.
TPM Emulation is considered unsafe and meant only for testing purposes.
For example, to enable tpm emulation with a static seed, disabling also
smbios headers:
```
rancheros:
tpm:
emulated: true
no_smbios: true
seed: "5"
```
It also adds a specific test for config file reading via ws with tpm.
Closes: https://github.com/rancher-sandbox/os2/issues/20
=> Enable TPM emulation

pkg/install/install.go
For some reason the installer was assuming that if you dont do an
automatic installation, your "extra data" from the config file should be
gone.
I do not understand why as automatic is not the same as providing a
config file with values which may have nothing to do with the
installation.
This patch removes the nulling of the extra data
Fixes #24 
=> Do not nullify the extra data from the config

Dockerfile
As we cannot clean the image afterwards due to it having scratch as
base, so no utils to rm, we are bringing several caches and metadata
from luet which kind of doubles the image size.
This patch reduces the image size to half by specifically copying the
required dirs in order to avoid bringing caches and repo files from luet
=> Reduce framework image by copying only needed files

pkg/config/read.go, pkg/config/read_test.go
During automated installation it was previously required to specify
either a containerImage or a isoUrl, but this is something we impose
ourselves, as elemental otherwise would install from the booting source.
Fixes: https://github.com/rancher-sandbox/cOS-toolkit/issues/1166
=> Do not require a container image or isoURL

.github/workflows/integration-tests.yaml, Dockerfile, Dockerfile.dapper, Dockerfile.kvm, framework/files/etc/cos/config, framework/files/etc/luet/luet.yaml, framework/files/system/oem/01_ros-rootfs.yaml, pkg/install/install.go, ros-image-build, tests/Makefile, tests/install/install_test.go, tests/smoke/smoke_test.go, tests/sut/sut.go
This PR disables `VERIFY` so mtree is not required (see #49).
Besides, tries to add a small test to make sure container image installation works, alongside it also rework the test to use `ros-installer` instead of `elemental install`.
=> Disable verify

.github/workflows/integration-tests.yaml
Upload iso, qcow, box and chart images individually so they can be
downloaded easier during development.
Fixes: #37
=> ci: Split upload of testing artifacts

cmd/ros-installer/main.go, pkg/config/config.go, pkg/install/install.go
Leverage the elemental CLI flag that allows to eject the cd when
restarting
This is part 3 of https://github.com/rancher-sandbox/os2/issues/31
Requires: https://github.com/rancher-sandbox/cOS-toolkit/pull/1191
Requires: https://github.com/rancher-sandbox/elemental/pull/156
=> Add flag for ejecting the cd when restarting

.github/workflows/integration-tests.yaml
It makes no sense as we upload them twice and we only need the iso/box
in the following jobs
=> Do not upload iso/qcow/box with the artifacts - do not download all artifacts for test

docs/architecture.md, docs/customizing.md, docs/installation.md, docs/upgrade.md, ros-image-build
- Export DOCKER_BUILDKIT=1 in the ros-image-build script so users dont
need to
- Update references to ranchor/os2 to rancher-sandbox/os2
- Update references to os2 images to point to quay
- Some minor changes in phrasing
Fixes https://github.com/rancher/os2/issues/17
Fixes https://github.com/rancher-sandbox/os2/issues/51
=> Fix ros-image-build and update docs

.github/workflows/install-with-rancher.yaml, framework/files/etc/systemd/system/rancherd.service.d/override.conf, tests/scripts/add-node-in-cluster, tests/scripts/configure-rancher-step-01, tests/scripts/install-rancher, tests/scripts/install-ros-node
These fixes/modifications were done during my cirrus-ci tests and could be useful for GHA tests.
=> Backport some fixes from cirrus-ci tests

.github/workflows/install-with-rancher.yaml, .github/workflows/integration-tests-manual.yaml, .github/workflows/integration-tests.yaml, .github/workflows/static_analisys.yaml, .github/workflows/tests.yaml
Should fix #61.
This PR also force Golang v1.17.x
=> ci: use new runner for bootstrap test + force Golang v1.17.x

tests/e2e/bootstrap_with_rancher_test.go
iPXE file is not in `test` directory, but in os2 root.
=> ci: fix iPXE file path for e2e test

Makefile
Otherwise fails for the permissions while committing changes
=> Fixup update framework permissions

.github/workflows/e2e-tests.yaml, tests/e2e/bootstrap_test.go, tests/e2e/upgrade_test.go
It's not RancherOS nor OS2.
This PR also fix the missing yaml file for UpgradeChannel test.
Verification run: https://github.com/rancher/elemental/actions/runs/2457512116
=> ci/e2e: fix worflow ARCH issue and test name

.github/workflows/integration-tests.yaml
Use the same values from the image push in the test-installer so they
both point to the same image built during testing
=> Set proper container repo for testing

framework/files/system/oem/05_motd_and_autologin.yaml
also rename the file to reflect its purpose
=> Fix the motd message

framework/files/system/oem/01_elemental-rootfs.yaml
This esp. allows proper tracking of local plans
Part of #171
=> Make /var/lib/elemental persistent

.gitignore, cypress.json, cypress/integration/unit_tests/first_connection.spec.ts, cypress/integration/unit_tests/menu.spec.ts, cypress/plugins/index.ts, cypress/support/elemental.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/toplevelmenu.ts, package.json, tsconfig.json
Fix #184 
Fix #185 
This PR adds Cypress tests but they are not configured in the CI yet (https://github.com/rancher/elemental/issues/199).
You can execute the tests only from your laptop with the right environment.
Video of the test:
[menu.spec.ts.zip](https://github.com/rancher/elemental/files/9159527/menu.spec.ts.zip)
=> Add Cypress tests into the repo

Makefile
Of course we dont have access to that file, we need to copy it if we are
passing a config into the iso/config so ti can be picked up on the image
build, just like on the elemental-iso-build
NOTE: this only affects building local isos from scratch, i.e. not with OBS artifacts so end-users isos should not be affected.
=> Fix custom cloud config while building iso

framework/files/system/oem/99_elemental-operator.yaml
This commit makes a better use of systemd-cat and it also
makes elemental-operator to be executed on network.after stage.
There is a race condition while calling `elemental install` in
network stage. This is an attempt to avoid it.
=> Improve elemental-operator call

framework/files/etc/luet/luet.yaml
We cant track a fixed repo on github builds as we would be really far
aways from latest elemental packages
This meant that on github builds, where we install elemental from teal repos instead of OBS, we were reaaaally behind the latest packages
=> Bump repo for teal packages

framework/files/system/oem/01_elemental-rootfs.yaml
Avoid the use of 'cdrom' provider for datasource plugin. This provider
opens all available block devices to probe them, however an `lsof` call
shows they are not closed afterwards. This might cause issues if within
the same process we pretend to repartition a disk for installation.
This is a workaround for rancher/elemental-operator#50
=> Do not use cdrom provider datasource

iso/grub.cfg
**Note:** iPXE boot script generated in `Makefile` will be fixed in PR #201.
=> build: remove obsolete elemental.install.* options

cypress.json, cypress/integration/unit_tests/machine_registration.spec.ts, cypress/plugins/index.ts, cypress/support/functions.ts, cypress/support/index.ts, package.json, tsconfig.json
Fix #196 
I can create a machine registration but I cannot check that they appear in the UI because they are with the attribute `disabled`
Stuck due to this bug anyway https://github.com/rancher/dashboard/issues/6458
=> Add Cypress tests for Machine Registration

framework/files/system/oem/01_elemental-rootfs.yaml
calico pods were looking for some data in /var/lib/calico but that is
not a persistent path, so it was failing to start.
Fixes https://github.com/rancher/elemental/issues/218
=> Fix rke2 deployments on restart

framework/files/usr/lib/systemd/system/elemental-system-agent.service
oneshot service unit type is not active until the executed cmd ends,
however the system agent is a service and polls for plans in an
infinite loop. A simple type is more appropriate, also adding restart
in case something fails contacting to the management cluster.
=> Improve service unit file

.github/workflows/image.yaml
Push the created images from master to the
quay.io/costoolkit/elemental-ci repo to have dev images published so we
can easily build isos from them to test them
=> Push master images to elemental-ci

Dockerfile.image, Makefile
For building the image locally/dev/github ci just use a fixed
elemental-cli image to get the elemental-cli binary instead of having to
wait for elemental-toolkit to publsih the packages so we can easily
change versions and test unpublished versions
Also add the GRUB_ENTRY_NAME to os-release so grub looks nicer
Fixes https://github.com/rancher/elemental/issues/176
=> Pick elemental from the docker image and set grub name

.github/workflows/e2e.yaml, tests/e2e/README.md, tests/e2e/bootstrap_test.go, tests/e2e/helpers/misc/misc.go, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/e2e/upgrade_test.go
Our self-hosted runner can be slow sometimes (SSD might be needed!), this PR adds a funciton to increase the timeout easily based on a env variable (`TIMEOUT_SCALE`). Set it to 2, should be enough (but will see after testing).
This PR also fixes small issues.
=> E2E: add SetTimeout function for slow runner

framework/files/etc/systemd/system/multi-user.target.wants/elemental-system-agent.service, framework/files/system/oem/99_elemental_system_agent.yaml, framework/files/usr/lib/systemd/system/elemental-system-agent.service
We should prevent having enabled services within the image unless we are fully confident we want them to be always enabled and running. Having services enabled just for the bootstrap phase is risky IMHO, as this is written within the immutable filesystem, we should only call the service when needed without enabling it.
=> Do not enable elemental-system-agent.service

framework/files/system/oem/01_elemental-rootfs.yaml
Every time when we want to write configurarion file in /usr/loca/etc
directory has to be checked and created properly.
Otherwise we will see
```
Running stage: initramfs
Executing /system/oem/01_elemental-rootfs.yaml
Applying 'Elemental Rootfs Layout Settings' for stage 'initramfs'. Total stages: 3
Processing stage step ''. ( commands: 1, files: 0, ... )
Command output: sh: line 1: /usr/local/etc/hostname: No such file or directory
Processing stage step 'Persist /etc/machine-id'. ( commands: 1, files: 0, ... )
Command output:
Processing stage step 'Create essential persistent paths'. ( commands: 0, files: >
```
=> Improve logic for 01_elemental-rootfs.yaml

docs/upgrade.md, examples/quickstart/registration.yaml, examples/quickstart/selector.yaml, examples/upgrade/managed-os-version-channel-custom.yaml, examples/upgrade/managed-os-version-channel-json.yaml, examples/upgrade/upgrade-cluster-target.yaml, examples/upgrade/upgrade-managedos-version.yaml, examples/upgrade/upgrade-node-selector.yaml
Fixes #241 
- Make them more consistent
- Mark the different paths in upgrading nodes
- Explain what the managedosversions are
- Explain what the managedosversionchannels are
- Add examples for everything
- Explain the types of syncers for managedosversions
- Add the discovery plugin for managedosversionchannels
=> Update upgrade docs

framework/files/usr/sbin/suc-upgrade
After elemental upgrade we have to also copy /etc/resolv.conf
from /host filesystem, otherwise  it will be taken from
container context.
Fixes https://github.com/orgs/rancher/projects/9
=> Copy /etc/resolv.conf from host during upgrade

.github/workflows/e2e.yaml, tests/e2e/bootstrap_test.go, tests/e2e/install_test.go, tests/scripts/install-vm
The E2E tests can be run directly on the self-hosted runner without using a container. This will speed up (a little) the run but more importantly will simplify the debugging in case of issue.
Verification run on my local lab: https://github.com/ldevulder/elemental/actions/runs/2911667003
=> e2e: don't use a container anymore

.github/workflows/ui-e2e.yaml, Makefile, scripts/install_rancher.sh, scripts/start_cypress_tests.sh
Fix #199 
This PR adds our first Cypress test in the CI, I installed a new self hosted runner within our DC.
https://github.com/rancher/elemental/runs/7991424029?check_suite_focus=true
Bash code will be migrated in Golang in a separate PR.
=> Add Cypress tests in the CI

.github/workflows/e2e.yaml, tests/e2e/bootstrap_test.go, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/e2e/upgrade_test.go
Should fix #248.
Verification run on my lab (limited to 2 nodes, 3 killed my laptop): https://github.com/ldevulder/elemental/actions/runs/2920853424
=> e2e: create rke2 cluster

README.md
Add a badge to be able to quickly check e2e tests status.
=> Add status badge for e2e tests

Dockerfile.image
Bump the base os image to 5.3
Fixes https://github.com/rancher/elemental/issues/297
=> Bump sle micro to 5.3

Dockerfile.image, framework/files/system/oem/99_networking.yaml
For github ci we need networkmanager enabled as our base image now ships with networkmanager by default, but its not enabled.
On OBS we already ship a packages that enables/disables services so we only need to enable networkmanager for dev and CI builds by setting it into the dockerfile
Fixes #319 
=> network: Enable networkmanager on dockerfile

docs/machineregistration-reference.md
We removed that field as duplicated of machineInventoryLabels. Update the docs accordingly.
=> docs: drop config:elemental:registration:labels field

elemental-iso-build
- Drop BASENAME as its not used
- Fix duplicated arg on curl manifest
- Add TAG var to be able to override where the artifacts come from
=> Fix script and enhance it

.github/workflows/e2e.yaml, examples/upgrade/upgrade-node-selector.yaml, tests/assets/managedOSVersionChannel.yaml, tests/assets/osVersions.json, tests/e2e/bootstrap_test.go, tests/e2e/configure_test.go, tests/e2e/helpers/misc/misc.go, tests/e2e/suite_test.go, tests/e2e/upgrade_test.go
This test will also use nodeSelector to restrict the upgrade to a specified node.
Should fix https://github.com/rancher/elemental/issues/298.
Verification run on my lab: https://github.com/ldevulder/elemental/actions/runs/3084596304
=> ci/e2e: re-add upgrade with managedOSVersionName

.github/workflows/e2e.yaml, .github/workflows/master-e2e.yaml, tests/e2e/bootstrap_test.go
Provisioning nodes with K3s should also be tested (RKE2 is already).
Should fix https://github.com/rancher/elemental/issues/339.
Verification run: https://github.com/ldevulder/elemental/actions/runs/3098196040\
*NOTE:* a renaming of the jobs have been done, but the verification run hasn't been restarted for this.
=> ci/e2e: add K3s cluster provisioning test

docs/quickstart.md
We moved it under the .github directory.
Fixes #362
=> docs: fix the elemental-iso-build link

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Fixes https://github.com/rancher/elemental/issues/312
=> Add Elemental issue templeate

.github/workflows/master-e2e.yaml
v1.23.10+k3s1 should be used instead of v1.23.10+k3s2...
=> ci/e2e: fix wrong K3s version

.github/workflows/e2e.yaml, tests/e2e/bootstrap_test.go
This is to avoid such kind of issue: https://github.com/rancher/elemental/actions/runs/3143967408/jobs/5110106627.
=> E2e increase timeout

.github/workflows/master-e2e.yaml, tests/assets/net-default.xml, tests/scripts/install-vm
Should fix https://github.com/rancher/elemental/issues/340.
Verification run: https://github.com/ldevulder/elemental/actions/runs/3150802958 (only one node, my lab is not powerful enough to test the whole stack).
=> ci/e2e: use EFI firmware instead of deprecated BIOS

framework/files/usr/lib/systemd/system/elemental-system-agent.service
This is a workaround for #374: when stopping the elemental-system-agent service, we will wait 10 seconds to tear down the service (which will likely be performed by the newly spawned rancher-system-agent). Let's elemental-system-agent have a bit of seconds more to mark completed the rancher-system-agent startup plan.
=> elemental-system-agent: delay the service stop of few seconds

.github/workflows/ui-e2e.yaml
With current version a running UI E2E test will be canceled if a CLI E2E test starts, which is not good and due to a copy/paste error.
=> ci/ui: use a different group than the CLI E2E tests

.github/workflows/e2e.yaml, .github/workflows/ui-e2e.yaml
Finally it's better to keep UI+CLI E2E tests in the same group, to avoid weird kill of running/pending tests.
The new behaviour will be this one:
- if nothing is running in the group then the submitted job will be scheduled and started
- if a job is already running then the submitted job will scheduled and set in pending state
- if a job is already running AND if there is already a scheduled test in pending test then the new submitted job will be scheduled, set in pending state and the former pending one will be canceled.
So only a running test and a pending one will be allowed for the same group.
This is mainly to protect the tests in `main` branch, to be able to have E2E CLI tests and UI at the same time. PR should not be too impacted as there is no UI test automatically scheduled, but …
=> Fix e2e tests group

.github/workflows/ui-e2e.yaml
Fix #398 
https://github.com/rancher/elemental/actions/runs/3198051962
This test failed but for a reason (the sporadic issue I got) external to this PR, we can see that the job was executed on the new runner.
This PR changes the runner used for UI testing, actually it is dedicated to UI.
The instance is configured as a spot instance to save money (153$ per month instead of 311$)
=> Use a dedicated runner for UI test (spot VM)

.github/workflows/e2e.yaml
Same as https://github.com/rancher/elemental/pull/401 but for the backend e2e tests.
=> Use GCP spot instance for the backend e2e CI

docs/backup.md, mkdocs.yml
Fixes https://github.com/rancher/elemental/issues/396
=> Add procedure howto backup elemental CRD resources

.github/workflows/build-ci.yaml, .github/workflows/e2e-obs-Dev.yaml, .github/workflows/e2e-obs-Staging.yaml, .github/workflows/e2e.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-e2e.yaml, tests/e2e/bootstrap_test.go, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/scripts/install-vm
Should fix https://github.com/rancher/elemental/issues/147 and https://github.com/rancher/elemental/issues/412.
- with [OBS artifacts on K3s](https://github.com/ldevulder/elemental/actions/runs/3275150151/jobs/5389624884)
- with [OBS artifacts on RKE2](https://github.com/ldevulder/elemental/actions/runs/3276459166/jobs/5392588725)
- with [GH artifacts on K3s](https://github.com/ldevulder/elemental/actions/runs/3275646007/jobs/5392027192)
- with [GH artifacts on RKE2](https://github.com/ldevulder/elemental/actions/runs/3277034771/jobs/5393798476)
**NOTE:** no UI verification run, as the UI-E2E tests are already broken...
=> ci/e2e: add boot iso and operator upgrade

.github/workflows/master-e2e.yaml
This should fix the download issue we see in CI.
=> ci/e2e: force HTTP1.1 for curl download

.github/workflows/ui-e2e.yaml
Different runner for UI tests so we need to use a different group.
=> Use a dedicated group for UI tests

.github/workflows/e2e-obs-Stable.yaml, .github/workflows/e2e-obs-Staging.yaml
Useful to test stable artifacts built on OBS.
=> ci/e2e: add E2E test for OBS Stable

.github/workflows/master-e2e.yaml
To avoid sporadic failure like this one: https://github.com/rancher/elemental/actions/runs/3312488264/jobs/5477683940
Tested locally, I'm not sure that this will fix the issue TBH, but at least there's no regression.
=> ci/e2e: add retry on curl command

.github/workflows/master-e2e.yaml
wget handles retry better than curl!
=> ci/e2e: better to use wget instead curl

framework/files/etc/NetworkManager/conf.d/rke2-canal.conf
According to rke2 docs NM can interfere with CNI routing.
This patch adds a config file so NM ignores devices from both calico and flannel
Fixes #446 
=> Network: Make NM ignore calico and flannel devices

.github/workflows/build-ci.yaml, .github/workflows/image.yaml, .github/workflows/integration.yaml, .github/workflows/master-e2e.yaml
=> ci: Fix github deprecations

.github/workflows/e2e-obs-Dev.yaml, .github/workflows/e2e-obs-Stable.yaml, .github/workflows/e2e-obs-Staging.yaml, .github/workflows/e2e.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-e2e.yaml, tests/e2e/bootstrap_test.go, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/scripts/config-private-ca
Add a test that use private CA instead of selfsigned in RKE2 E2E test.
Should fix #429
Verification run: https://github.com/rancher/elemental/actions/runs/3336651585
Verification run for the refactoring commit: https://github.com/ldevulder/elemental/actions/runs/3337939442
=> ci/e2e: add Private CA test with Rancher Manager

docusaurus.config.js
Due to the docs being a sub-directory, the Docusaurus configuration needs to update the `baseUrl`.
=> Updated baseUrl to match the docs sub-directory

docs/installation.md, framework/files/system/oem/01_elemental-rootfs.yaml
SLE Micro 5.3 replaces wicked with NetworkManager.
https://www.suse.com/releasenotes/x86_64/SLE-Micro/5.3/index.html
=> Update persistent paths for NetworkManager

.github/workflows/master-e2e.yaml
Because the UI test doesn't use `node_number` variable and thus it will always return the default value (5) as the number of installed nodes, which is false.
See here for an example of a bad output: https://github.com/rancher/elemental/actions/runs/3422527311.
=> ci/ui: remove number of installed nodes from summary

docusaurus.config.js
The Algolia search crawler has been configured and the search bar can now be used.
Another small change to the configuration was also done for the URL and baseURL settings to avoid a warning when building the docs website.
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>
=> Added Algolia search bar

.github/workflows/master-e2e.yaml, cypress/e2e/unit_tests/machine_registration.spec.ts, cypress/e2e/unit_tests/machine_selector.spec.ts, cypress/fixtures/custom_cloud-config.yaml, cypress/support/e2e.ts, cypress/support/functions.ts, tests/e2e/ui_test.go
Due to a bug with cloud-config, until now, we were using a machine registration not created in the UI but the same as the backend e2e test (https://github.com/rancher/elemental/blob/main/tests/assets/machineregistration.yaml).
It sound more logical to run the test with a machine registration created with the UI.
This PR adds a test in machine registration to create the resource we need to deploy a node.
Actually, it also tests the cloud config block because we have to import our custom cloud config there.
Fix #215 
https://github.com/rancher/elemental/actions/runs/3427858809
=> Use machine reg created in UI instead of the one in test assets

cypress/e2e/unit_tests/machine_registration.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts
This test makes sure that the default cloud-config exist after creating a machine registration.
Regression test to avoid this bug https://github.com/rancher/elemental-ui/issues/15
https://github.com/rancher/elemental/actions/runs/3436098148
=> Add UI test to check default cloud-config

examples/upgrade/upgrade-node-selector.yaml
The smbios labels are not propagated to the nodes, so `location` cannot be used for nodeSelector in any meaningful way.
=> docs: Change nodeSelector example

.obs/workflows.yml
This commit sets the OBS workflow to also rebuild Dev environment when a tag is pushed to main branch. This is relevant to ensure the latest Dev build is also taking the correct package version.
=> Also trigger Dev rebuild on tag push

Dockerfile.image
We are overriding the existing values in the os-release file and we
should not. We already have the IMAGE_TAG and/or COMMIT to check the
versions
Also adds the TIMESTAMP to os-release
Both are done to be more in sync with OBS builds.
=> Do not overwrite VERSION/VERSION_ID on dockerfile build

.github/workflows/e2e-obs-Dev.yaml, .github/workflows/e2e-obs-Stable.yaml, .github/workflows/e2e-obs-Staging.yaml
Also set `latest/devel` version as the default one (but this can be changed upon triggered).
Verification run: https://github.com/rancher/elemental/actions/runs/3482867640
=> ci/e2e: make Rancher version configurable

.github/workflows/master-e2e.yaml, cypress/e2e/unit_tests/advanced_filtering.spec.ts, cypress/fixtures/machine_inventory_1.yaml, cypress/fixtures/machine_inventory_2.yaml, cypress/fixtures/machine_inventory_3.yaml, cypress/support/e2e.ts, cypress/support/functions.ts
Fix #514
Details of the new tests:
1. Create 3 machine inventories with different labels to play with.
2. Filtering on `test-filter`, two items should match.
3. Filtering on `test-filter-one`, one item should match.
4. Filtering on `test-wrong-filter`, no item should match and UI should not crash ( regression test to catch https://github.com/rancher/elemental-ui/issues/41)
https://github.com/rancher/elemental/actions/runs/3541232883/jobs/5945256342
The failure is related to the upgrade issue, nothing linked to this PR.
=> Test advanced filtering in Elemental UI

cypress/e2e/unit_tests/advanced_filtering.spec.ts
Fake machine inventories must be removed, otherwise, next tests fail.
Whereas we catch `Matches all 1 existing Inventory of Machines` in the selector test....
https://github.com/rancher/elemental/actions/runs/3541966519
The failure is related to the upgrade issue, nothing linked to this PR.
=> Remove fake machine inventories (Cypress tests)

.github/workflows/e2e-obs-Dev.yaml, .github/workflows/e2e-obs-Stable.yaml, .github/workflows/e2e-obs-Staging.yaml
The new operator URI is now aligned with other Rancher charts. This PR also allows the value to be overwritten.
=> ci/e2e: use new elemental-operator helm chart

cypress/e2e/unit_tests/machine_registration.spec.ts, cypress/e2e/unit_tests/upgrade.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts
Fix #500
Testing removing OS versions ans OS version channel in the UI e2e tests.
Replace `deleteAllMachReg` function by a more generic one (`deleteAllResources`).
Verification run: :heavy_check_mark: 
https://github.com/rancher/elemental/actions/runs/3592921748/jobs/6049234957
=> Delete OS version and channel in e2e UI tests

docs/architecture.md, docs/backup.md, docs/cloud-config-reference.md, docs/cluster-reference.md, docs/customizing.md, docs/elemental-plans.md, docs/elementaloperatorchart-reference.md, docs/index.md, docs/installation.md, docs/inventory-management.md, docs/kubernetesversions.md, docs/machineinventoryselectortemplate-reference.md, docs/machineregistration-reference.md, docs/quickstart.md, docs/restore.md, docs/smbios.md, docs/tpm.md, docs/troubleshooting-restore.md, docs/upgrade.md, package.json
Redirect configuration:
from: rancher.github.io/elemental/*
to: elemental.docs.rancher.com
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>
=> Added redirect to new URL on all pages

tests/assets/machineregistration.yaml
With the current kubebuilder branch the operator complains if unknown values are passed. On former code they were simply ignored.
=> Automatic is no longer a valid value

.github/workflows/master-e2e.yaml, .github/workflows/ui-e2e-k3s.yaml, .github/workflows/ui-e2e-rke2.yaml
Convert the `runner_template` env variable to an input one. 
Like that, it will be easier to use another instance template.
VR:
[k3s UI test with n2-standard-16](https://github.com/rancher/elemental/actions/runs/3619255818)
=> Convert runner_template to input variable

README.md
Badges have to be updated as we have split the tests into small ones dedicated to either k3s or RKE2.
=> Update README CI badges

.github/workflows/e2e-k3s-obs-Dev.yaml, .github/workflows/e2e-k3s-obs-Stable.yaml, .github/workflows/e2e-k3s-obs-Staging.yaml, .github/workflows/e2e-rke2-obs-Dev.yaml, .github/workflows/e2e-rke2-obs-Stable.yaml, .github/workflows/e2e-rke2-obs-Staging.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-e2e-k3s.yaml, .github/workflows/ui-e2e-rke2.yaml
This commit also remove some unneeded `S{{ .. }}` syntaxes.
Verification run: https://github.com/rancher/elemental/actions/runs/3619937740
=> ci/e2e: only send Slack notification on schedule

tests/assets/machineregistration.yaml, tests/assets/managedOSVersionChannel.yaml, tests/e2e/bootstrap_test.go, tests/e2e/helpers/misc/misc.go, tests/e2e/install_test.go, tests/e2e/upgrade_test.go
This should fix #565.
Verification Run (operator Dev version): https://github.com/rancher/elemental/actions/runs/3642668127
Verification Run (operator Stable version): https://github.com/rancher/elemental/actions/runs/3643034043
=> ci/e2e: fix failure with KubeBuilder version of operator

.github/workflows/master-e2e.yaml
Our GH runners are now ephemeral, they are deleted after each run so we do not need paying attention to clean them.
=> Remove two CI steps not needed anymore due to ephemeral GH runners

cypress/e2e/unit_tests/elemental_plugin.spec.ts
Fix #579 
Disable the rancher extension repository to be able to install elemental-ui from a dev repository.
https://github.com/rancher/elemental/actions/runs/3693433209
=> Disable Rancher extension repository in UI tests

.github/workflows/ui-e2e-k3s-obs-Dev.yaml, .github/workflows/ui-e2e-k3s-obs-Stable.yaml, .github/workflows/ui-e2e-k3s-obs-Staging.yaml, .github/workflows/ui-e2e-rke2-obs-Dev.yaml, .github/workflows/ui-e2e-rke2-obs-Stable.yaml, .github/workflows/ui-e2e-rke2-obs-Staging.yaml
Fix #580 
With this PR, we will be able to manually trigger e2e UI tests on many OBS artifacts like dev, staging and stage like we do for e2e CLI.
Verification Run:
[k3s OBS Dev](https://github.com/rancher/elemental/actions/runs/3695822413/jobs/6258727210)
[k3s OBS Staging](https://github.com/rancher/elemental/actions/runs/3696729959/jobs/6263407056)
=> Add dev, staging and stage scenarios for UI e2e

.github/workflows/e2e-k3s-obs-Dev.yaml, .github/workflows/e2e-k3s-obs-Stable.yaml, .github/workflows/e2e-k3s-obs-Staging.yaml, .github/workflows/e2e-rke2-obs-Dev.yaml, .github/workflows/e2e-rke2-obs-Stable.yaml, .github/workflows/e2e-rke2-obs-Staging.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-e2e-k3s-obs-Dev.yaml, .github/workflows/ui-e2e-k3s-obs-Stable.yaml, .github/workflows/ui-e2e-k3s-obs-Staging.yaml, .github/workflows/ui-e2e-k3s.yaml, .github/workflows/ui-e2e-rke2-obs-Dev.yaml, .github/workflows/ui-e2e-rke2-obs-Stable.yaml, .github/workflows/ui-e2e-rke2-obs-Staging.yaml, .github/workflows/ui-e2e-rke2.yaml, tests/assets/cluster.yaml, tests/assets/machineRegistration.yaml, tests/assets/selector.yaml, tests/e2e/bootstrap_test.go, tests/e2e/configure_test.go, tests/e2e/helpers/misc/misc.go, tests/e2e/suite_test.go, tests/e2e/upgrade_test.go
Use a "master" pool for the first 3 nodes and a "worker" pool for all others.
Should fix #531.
- [OBS Stable - RKE2 - Elemental UI End-To-End tests with Rancher Manager](https://github.com/rancher/elemental/actions/runs/3713901006)
- [OBS Stable - RKE2 - Elemental E2E tests with Rancher Manager](https://github.com/rancher/elemental/actions/runs/3713954273)
- [OBS Stable - K3s - Elemental E2E tests with Rancher Manager](https://github.com/rancher/elemental/actions/runs/3715364100)
- [OBS Dev - K3s - Elemental E2E tests with Rancher Manager](https://github.com/rancher/elemental/actions/runs/3716567199) - It fails because of this [operator issue](https://github.com/rancher/elemental-operator/pull/307)
Non Regression tests on UI: …
=> ci/e2e: use 2 pools for cluster provisioning

.github/workflows/master-e2e.yaml
Cypress has been moved into the tests folder, so we also need to update the PATH for Cypress artifacts used in the upload action.
VR: https://github.com/rancher/elemental/actions/runs/3794824595
=> Fix path for Cypress artifacts upload

.github/workflows/master-e2e.yaml, .github/workflows/update-tests-description.yaml
We have to use a token to allow commit's push on main branch.
Tested on my lab after adding the same restrictions on my `main` branch:
- [test with branch locked and no token](https://github.com/ldevulder/gha-tests/actions/runs/3806093679)
- [test with branch locked and token used](https://github.com/ldevulder/gha-tests/actions/runs/3806100777/jobs/6474599340)
=> ci: fix generated README for tests description

.github/workflows/e2e-k3s-obs-Dev.yaml, .github/workflows/e2e-k3s-obs-Stable.yaml, .github/workflows/e2e-k3s-obs-Staging.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-e2e-k3s.yaml, tests/assets/squid.conf, tests/cypress/e2e/unit_tests/machine_inventory.spec.ts, tests/cypress/plugins/index.ts, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/scripts/start-cypress-tests
Fix #492 
1) Elemental node behind a proxy (most important one FMPOV)
2) Rancher manager behind the proxy
It is a simple container running on the github runner:
`docker run -d -v $(pwd)/tests/assets/squid.conf:/etc/squid/squid.conf -p 3128:3128 wernight/squid`
And the proxy is reachable via `192.168.122.1:3128`, a new firewall rule has been added to GCP to allow tcp traffic on port 3128.
https://github.com/rancher/elemental/actions/runs/3799671144 :heavy_check_mark: 
Proxy's log:
```
1672310331.838  54394 172.17.0.1 TCP_TUNNEL/200 204571 CONNECT elemental-ci-cf3e2af3-56dd-42de-8c08-c4ea1461d42f.us-central1-a.c.ei-container-eco.internal:443 - HIER_DIRECT/10.128.15.217 -
1672310331.838  54406 172.17.0.1 TCP_TUNNEL/200 2011 CONNECT elemental-ci-cf3e2af3-56dd-42de-8c08-c4ea1461d42f.us-central1 …
```
=> Add proxy tests in UI

.github/workflows/master-e2e.yaml
It was missing for `Store logs` step.
It should fix this [issue](https://github.com/rancher/elemental/actions/runs/3828137506/jobs/6513408580).
=> ci/ui: fix permissions for 'downloads' directory #2

.github/workflows/master-e2e.yaml, tests/cypress/e2e/unit_tests/machine_inventory.spec.ts, tests/e2e/logs_test.go
Fix #601 
1) k3s + elemental node behind proxy: :heavy_check_mark: 
https://github.com/rancher/elemental/actions/runs/3829106330/jobs/6515446391
Proxy log is in the support-logs archive
2) k3s + Rancher manager behind proxy: :heavy_check_mark: 
https://github.com/rancher/elemental/actions/runs/3829964335
=> Improve proxy tests

Dockerfile.iso, tests/assets/osVersions.json, tests/cypress/e2e/unit_tests/upgrade.spec.ts
`teal-5.2` image doesn't exist anymore, better to use a `fake-image` for UI upgrade test. This PR also fix the ISO build by using the correct images.
=> Fix ISO build and upgrade tests with managedOSVersionChannel 

.github/elemental-iso-add-registration, .github/workflows/build-iso-inject-pr.yaml
It fails on macOS, as Docker needs to be installed before buildx.
=> ci: fix "test inject in iso" workflow

tests/assets/osVersions.json
`stable` should be removed, as there is only one image for `elemental-node-image`.
=> ci/e2e: fix path to upgrade image

.github/elemental-iso-add-registration
Here I've added support for using Podman for the injection of registration information to the Elemental Teal ISO. This does not replace Docker as the default (if it's available on the client) but provides an option for those of us using Podman instead (bypassing the `alias docker=podman` hack). This has been tested on Tumbleweed with Podman and Ubuntu with Docker.
I have also cleaned up a little bit of whitespace that I found lingering.
=> Add support for Podman for registration injection into ISO

tests/install/install_test.go
The checked text has been slightly modified due to refactoring in elemental-cli. See https://github.com/rancher/elemental-cli/pull/404.
=> ci/integ: fix failing test

.github/workflows/e2e-k3s-latest.yaml, .github/workflows/e2e-k3s-obs-Dev.yaml, .github/workflows/e2e-k3s-obs-Stable.yaml, .github/workflows/e2e-k3s-obs-Staging.yaml, .github/workflows/e2e-k3s-stable.yaml, .github/workflows/e2e-rke2-latest.yaml, .github/workflows/e2e-rke2-obs-Stable.yaml, .github/workflows/e2e-rke2-obs-Staging.yaml, .github/workflows/e2e-rke2-stable.yaml, .github/workflows/ui-e2e-k3s-latest.yaml, .github/workflows/ui-e2e-k3s-obs-Dev.yaml, .github/workflows/ui-e2e-k3s-obs-Stable.yaml, .github/workflows/ui-e2e-k3s-obs-Staging.yaml, .github/workflows/ui-e2e-k3s-stable.yaml, .github/workflows/ui-e2e-rke2-latest.yaml, .github/workflows/ui-e2e-rke2-obs-Dev.yaml, .github/workflows/ui-e2e-rke2-obs-Stable.yaml, .github/workflows/ui-e2e-rke2-obs-Staging.yaml, .github/workflows/ui-e2e-rke2-stable.yaml, README.md
Fix #606 
The PR adds new workflow files to run nightly tests on top of latest stable Rancher manager instead of latest dev only.
Some files were also renamed to be fully viewable in the actions menu
Better with new names:
Latest RM: https://github.com/rancher/elemental/actions/runs/3940389848/jobs/6741517419
`docker.io/rancher/rancher:v2.7.2-rc1`
Stable RM: https://github.com/rancher/elemental/actions/runs/3940389857/jobs/6741499953
`docker.io/rancher/rancher:v2.7.0`
=> Run nightly CI tests on stable Rancher Manager

tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
Deprecated k8s versions need to be displayed to use same k8s versions as the test on latest stable rancher manager.
Verification run: https://github.com/rancher/elemental/actions/runs/3950601139 :heavy_check_mark:
=> e2e ui: show k8s deprecated versions

tests/cypress/e2e/unit_tests/deploy_app.spec.ts
This PR should fix a sporadic issue which happens when we check if the cis-benchmark app is deleted.
Broken test: https://github.com/rancher/elemental/actions/runs/3955300594/jobs/6773475455
I would like the test passes 3 times in a row to be sure it is not flaky anymore :smile: 
1)  https://github.com/rancher/elemental/actions/runs/3958665734 :heavy_check_mark: 
2) https://github.com/rancher/elemental/actions/runs/3959132781 :heavy_check_mark: 
3)  https://github.com/rancher/elemental/actions/runs/3960011054 :heavy_check_mark:
=> e2e ui: change how we check that an app is deleted

.github/workflows/master-e2e.yaml, tests/assets/emulateTPM.yaml, tests/e2e/bootstrap_test.go, tests/scripts/install-vm
As emulated TPM now works on more than one node, the seed is generated based on the server UUID.
This should fix #586.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/3984396725)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/3984400204)
=> ci/e2e: test emulated TPM on more than one node

.github/workflows/e2e-k3s-latest.yaml, .github/workflows/e2e-rke2-latest.yaml
This worflow is scheduled *after* build-ci to be sure that we have the lastest version built. The scheduling is also to avoid running the worklow on each push on main.
=> ci/e2e: don't run test on latest RM on every push

tests/cypress/e2e/unit_tests/upgrade.spec.ts
Fix #605 
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4004239136): :heavy_check_mark: 
[RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4004511104): :heavy_check_mark: Test failed for an external reason to this PR.
[K3s-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/3984636470/jobs/6831082377): :heavy_check_mark:  Test failed a little bit after but for an external reason to this PR.
[RKE2-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/3994321457): :heavy_check_mark: 
I'm lucky with the provided fix because it also works for older Rancher Manager versions so no need to introduce `if version ==` in the code.
=> e2e/ui: replace .xterm-cursor-layer in Cypress

.github/workflows/master-e2e.yaml, tests/e2e/bootstrap_test.go
If elemental-operator is version 1.0.x we should disable `EMULATE_TPM` as this version doesn't generate unique TPM seed.
This PR also temporary removed the upgrade tests for OBS-Stable artifacts because of isse #632.
- [OBS-Stable-K3s-E2E ](https://github.com/rancher/elemental/actions/runs/4016320699)
- [OBS-Stable-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4014810703)
- [OBS-Dev-K3s-E2E ](https://github.com/rancher/elemental/actions/runs/4015540608)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4009680078)
**NOTE:** OBS-Stable-K3s-E2E fails but not because of this PR. As the 3 other tests are OK I will check/fix the issue in another issue/PR.
=> ci/e2e: fix VM bootstrapping with OBS Stable

.github/workflows/e2e-k3s-obs-Dev.yaml, .github/workflows/e2e-k3s-obs-Stable.yaml, .github/workflows/e2e-k3s-obs-Staging.yaml, .github/workflows/e2e-rke2-obs-Dev.yaml, .github/workflows/e2e-rke2-obs-Stable.yaml, .github/workflows/e2e-rke2-obs-Staging.yaml, .github/workflows/master-e2e.yaml, tests/scripts/install-vm
We should reserved much more memory for UI tests.
- [K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4023151768)
- [RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4023154382)
- [RKE2-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4024402597)
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4024621102)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4024635315)
- [OBS-Staging-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4024389796)
- [OBS-Staging-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4025099008)
=> ci: fix UI tests with hugepages

tests/cypress/support/functions.ts
Fix #643 
https://github.com/rancher/elemental/actions/runs/4101679988 :heavy_check_mark: 
Wait 20 sec instead of 10 sec when we delete a machine registration in our e2e UI tests.
I also remove a useless 8 seconds timeout, as the default is 10, we do not need a lower timeout.
=> ci/e2e: increase timeout when delete resource in UI

.github/workflows/e2e-k3s-latest.yaml, .github/workflows/e2e-rke2-latest.yaml
E2E tests with latest/devel version of Rancher Manager are not scheduled because of wrong start_condition and workflow_download values.
=> ci/e2e: fix E2E scheduled tests with latest RMS

.obs/specfile/elemental.spec, Dockerfile.image, framework/files/usr/lib/systemd/system/shutdown-k3s.service
Seems to be hitting this issue: https://github.com/k3s-io/k3s/issues/2400
The workaround suggested is to add a service that runs k3s-killall before umount.
Fixes #587 
=> Add service to kill k3s before umount

.github/workflows/master-e2e.yaml
With the latest changes to run node provisioning in parallel it's now possible to test 10 nodes on the same runner and in the same time as we did with 5 nodes.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4116280399)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4113231429)
=> ci/e2e: increase default node number to 10

.github/workflows/e2e-k3s-hard-stable.yaml, .github/workflows/master-e2e.yaml, tests/assets/hardened_cluster/90-kubelet.conf, tests/assets/hardened_cluster/audit.yaml, tests/assets/hardened_cluster/networkpolicy.yaml, tests/assets/hardened_cluster/policy.yaml, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/scripts/config-hardened
Fix #604 
Instruction comes from https://docs.k3s.io/security/hardening-guide
[Hardened K3s](https://github.com/rancher/elemental/actions/runs/4164214683/jobs/7206478937)
[Standard K3s](https://github.com/rancher/elemental/actions/runs/4164623724/jobs/7206520230)
Documented in our documentation space :heavy_check_mark:
=> ci/e2e: add test on hardened cluster

.github/workflows/master-e2e.yaml
This reverts commit 14c71b38c39cc204879c41f3d2af8f6218329d8e.
This is done because we have sporadic failures with 10 nodes, more debugging is needed on this.
=> Revert "ci/e2e: increase default node number to 10"

.github/workflows/master-e2e.yaml, tests/assets/local-kubeconfig-skel.yaml, tests/assets/local-kubeconfig-token-skel.yaml, tests/cypress/e2e/unit_tests/machine_registration.spec.ts, tests/e2e/bootstrap_test.go, tests/e2e/configure_test.go, tests/e2e/helpers/misc/misc.go, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/e2e/ui_test.go, tests/e2e/upgrade_test.go
This is to be sure that all objects created with CLI commands are tagged with Rancher Manager user.
This should fix issue rancher/elemental-operator#310.
- [RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4183113727)
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4175511640)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4175824667)
**NOTE:** the test OBS-Dev-RKE2-E2E has failed because the VM has been killed by GCP (SPOT), but the PR is validated as the changes are done during Rancher Manager installation.
=> ci/e2e: use Rancher Manager Admin user for CLI commands

.github/workflows/master-e2e.yaml, tests/e2e/upgrade_test.go
Upgrade tests scenarii should be changed. As they are not relevant anymore and sporadically fail it better to disable them.
This commit also remove the manual upgrade test with Elemental CLI, as this is not supported. And anyway the others upgrade methods are using the same API for the upgrade as the CLI. It could also be added in elemental-toolkit if needed.
Should fix #668 and #669.
**NOTE:** upgrade test in UI is kept, as it does a test do the latest version built and check the generated OS list from YAML, so still useful for now.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4185423975)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4186904548)
=> ci/e2e: disable upgrade tests

.github/workflows/ui-e2e-k3s-stable.yaml, .github/workflows/ui-e2e-rke2-stable.yaml, tests/cypress/e2e/unit_tests/elemental_plugin.spec.ts, tests/cypress/e2e/unit_tests/machine_selector.spec.ts
Fix #663 
[Latest Rancher Manager K3s](https://github.com/rancher/elemental/actions/runs/4195698892/jobs/7275629665) - Failed on upgrade, not related to this PR
[Stable Rancher Manager K3s](https://github.com/rancher/elemental/actions/runs/4195699792/jobs/7275629833)
=> ci/ui: adapt cypress code to elem-ui 1.0.1

tests/cypress/e2e/unit_tests/upgrade.spec.ts
This PR disables upgrade test in our main scenario, we agreed to test upgrade in a separate test where we will use stable ISO and update to dev one.
=> ci/ui: Disable upgrade

.github/workflows/master-e2e.yaml, tests/assets/cluster.yaml, tests/e2e/bootstrap_test.go, tests/e2e/configure_test.go, tests/e2e/suite_test.go, tests/scripts/install-vm
This will reduce CI execution time.
Nodes 1, 2 and 3 will be installed using the ISO and emulated TPM on the *master* pool, and the other nodes will be installed using iPXE and hardware TPM on the *worker* pool.
- [RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4196674169)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4196402722)
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4196542635)
- [OBS-Staging-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4196763184)
- [OBS-Staging-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4196767180)
=> ci/e2e: install the 3rd first nodes all in parallel

.obs/specfile/elemental.spec, tests/cypress/e2e/unit_tests/advanced_filtering.spec.ts, tests/cypress/e2e/unit_tests/deploy_app.spec.ts, tests/cypress/e2e/unit_tests/elemental_plugin.spec.ts, tests/cypress/e2e/unit_tests/first_connection.spec.ts, tests/cypress/e2e/unit_tests/machine_inventory.spec.ts, tests/cypress/e2e/unit_tests/machine_registration.spec.ts, tests/cypress/e2e/unit_tests/machine_selector.spec.ts, tests/cypress/e2e/unit_tests/menu.spec.ts, tests/cypress/e2e/unit_tests/upgrade.spec.ts, tests/cypress/e2e/unit_tests/user.spec.ts, tests/cypress/plugins/index.ts, tests/cypress/support/e2e.ts, tests/cypress/support/elemental.ts, tests/cypress/support/functions.ts, tests/cypress/support/toplevelmenu.ts, tests/e2e/bootstrap_test.go, tests/e2e/configure_test.go, tests/e2e/helpers/misc/misc.go, tests/e2e/install_test.go, tests/e2e/logs_test.go, tests/e2e/suite_test.go, tests/e2e/ui_test.go, tests/e2e/upgrade_test.go, tests/install/install_suite_test.go, tests/install/install_test.go, tests/smoke/smoke_suite_test.go, tests/smoke/smoke_test.go
Adds 2023 in the range. This commit also adds copyright header where it was missing.
=> Fix copyright and date range

tests/e2e/logs_test.go
Failed tests: https://github.com/rancher/elemental/actions/workflows/ui-e2e-k3s-latest.yaml and https://github.com/rancher/elemental/actions/runs/4225773365/jobs/7339319440
The test which using proxy fails sporadically, we trap this `TCP_TUNNEL/200.*CONNECT git.rancher.io` and sometimes we cannot see it in the log, I checked and when we see it, it is the last line of the file so I'm thinking about a race condition there. We should check something else to make the test more resilient.
https://github.com/rancher/elemental/actions/runs/4231654361
https://github.com/rancher/elemental/actions/runs/4232912174
=> ci/ui: update regex to check proxy logs

.github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/cli-k3s-os-upgrade.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/cli-rke2-os-upgrade.yaml, .github/workflows/e2e-k3s-latest.yaml, .github/workflows/master-e2e.yaml, README.md, tests/assets/managedOSVersionChannel.yaml, tests/assets/upgrade_skel.yaml, tests/e2e/bootstrap_test.go, tests/e2e/suite_test.go, tests/e2e/upgrade_test.go
Should fix #670 and #671.
- [OBS-Stable-K3s-E2E-Upgrade](https://github.com/rancher/elemental/actions/runs/4236925512)
- [CLI-RKE2-Stable-RM_Stable-Upgrade](https://github.com/rancher/elemental/actions/runs/4241831890)
- [CLI-RKE2-Stable-RM_Stable-Upgrade with PrivateCA and Stable Operator](https://github.com/rancher/elemental/actions/runs/4242227097)
- [CLI-RKE2-Stable-RM_Stable-Upgrade with PrivateCA and Dev Operator](https://github.com/rancher/elemental/actions/runs/4242753691) -> it fails but it's not related to this PR, it will be checked later
- [CLI-K3s-OS-Upgrade with Upgrade Summary](https://github.com/rancher/elemental/actions/runs/4244959557)
=> e2e: add separate upgrade test

.github/workflows/master-e2e.yaml, .github/workflows/ui-k3s-os-upgrade.yaml, .github/workflows/ui-k3s-stable-rm_latest-upgrade.yaml, .github/workflows/ui-k3s-stable-rm_stable-upgrade.yaml, .github/workflows/ui-rke2-os-upgrade.yaml, .github/workflows/ui-rke2-stable-rm_latest-upgrade.yaml, .github/workflows/ui-rke2-stable-rm_stable-upgrade.yaml, README.md, tests/cypress/e2e/unit_tests/deploy_app.spec.ts, tests/cypress/e2e/unit_tests/machine_inventory.spec.ts, tests/cypress/e2e/unit_tests/upgrade.spec.ts, tests/cypress/plugins/index.ts, tests/e2e/logs_test.go, tests/scripts/start-cypress-tests
Fix #659 
[UI-K3s-Stable-RM_Latest-Upgrade](https://github.com/rancher/elemental/actions/runs/4247873025/jobs/7386410896) - This one failed for a reason external to the PR.
[UI-K3s-Stable-RM_Stable-Upgrade](https://github.com/rancher/elemental/actions/runs/4247873032/jobs/7386411012) :heavy_check_mark: 
[UI-RKE2-Stable-RM_Latest-Upgrade](https://github.com/rancher/elemental/actions/runs/4247873037/jobs/7386409520):heavy_check_mark: 
[UI-RKE2-Stable-RM_Stable-Upgrade](https://github.com/rancher/elemental/actions/runs/4247873028/jobs/7386412170):heavy_check_mark: 
- cluster renamed from `myelementalcluster` to `mycluster` due to this bug https://github.com/rancher/elemental-operator/issues/365
- update the regex which is making sure we went through proxy
=> ci/ui: add UI upgrade test back

tests/assets/selector.yaml, tests/e2e/configure_test.go
Just add a value in the selector list to validate that the issue faced in rancher/elemental-operator#352 will not happen again.
Should fix #672.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4251423301)
- [OBS-Stable-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4251239429)
=> ci/e2e: add regression test for elemental-operator#352

.github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, README.md
This PR fixes bad `links/tests names` for github badges introduced by https://github.com/rancher/elemental/pull/683.
=> ci/ui: fix ui upgrade tests names to match README

.github/workflows/master-e2e.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade.yaml, tests/cypress/e2e/unit_tests/upgrade.spec.ts, tests/cypress/plugins/index.ts, tests/scripts/start-cypress-tests
Fix issue with OS channel tests: https://github.com/rancher/elemental/actions/runs/4249379692/jobs/7389488389
First thing is moving those tests in the upgrade scenario instead of main.
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4253058702) :heavy_check_mark: 
[K3s-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4253067554) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4253417339) :heavy_check_mark: 
[UI-RKE2-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4253410532) :heavy_check_mark:
=> ci/ui: group all upgrade tests in upgrade scenario

.github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/cli-rke2-os-upgrade.yaml, .github/workflows/master-e2e.yaml, tests/e2e/bootstrap_test.go
Sometimes the MachineInventory is empty on the first try, better to check it in a loop with a timeout.
- [CLI-RKE2-OS-Upgrade](https://github.com/rancher/elemental/actions/runs/4254057925)
- [CLI-K3s-OS-Upgrade](https://github.com/rancher/elemental/actions/runs/4254218258)
- [OBS-Stable-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4255914779)
=> ci/e2e: fix a sporadic issue when retrieving server id

framework/files/usr/sbin/suc-upgrade
This partially fixes rancher/elemental-operator#364. It prevent two concurrent upgrade procedures within the same node. Since this is at node level this is not a full fix as two different upgrade procedures happening at the same time in different nodes of the same cluster is still possible. IMHO the solutions should focus of preventing any concurrency at cluster level.
In any case this solves the ugliest issue, which is having two simultaneous `elemental upgrade` calls over the same node simultaneously.
=> No concurrent suc upgrade

.github/workflows/ui-e2e-rke2-latest.yaml, .github/workflows/ui-e2e-rke2-obs-Dev.yaml, .github/workflows/ui-e2e-rke2-obs-Stable.yaml, .github/workflows/ui-e2e-rke2-obs-Staging.yaml, .github/workflows/ui-e2e-rke2-stable.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade.yaml
As https://github.com/rancher/elemental-ui/issues/64 is fixed, we can remove the user workaround to run RKE2 test as elemental-user instead of admin.
elemental-user test is disabled in tests where we use elemental-ui (1.0.0 - stable), we will enable it when a new stable will be released.
[RKE2-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4304252795) :heavy_check_mark: 
[RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4304254380) :heavy_check_mark:
=> ci/ui: remove user workaround in RKE tests

framework/files/usr/sbin/suc-upgrade
This commit sorts the current OS version with the one we aim to upgrade to. If the OS to be upgraded to is not higher than the current one it assumes we are up to date and the upgrade script exits 0. This causes the upgrade plan to succeed and to be considered as upgraded. This is to fix https://github.com/rancher/elemental-operator/issues/364#issuecomment-1443139017
Alternatively if a downgrade is required it is still possible, but requires a customized `Update Group` (`ManagedOSImage` crd) to include the `FORCE` environment variable within the upgrade script:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
name: upgrade3
namespace: fleet-default
spec:
clusterTargets:
- clusterName: my-cluster
upgradeContainer:
command:
- "/usr/sbin/suc-upgrade"
envs:
- …
```
=> Do not allow downgrades without force flag

.github/workflows/master-e2e.yaml, tests/cypress/e2e/unit_tests/upgrade.spec.ts
Fix #696 
- If test uses elemental-ui `1.0.0`, we cannot test upgrade with OS version channel, so we test upgrading with OS image only both for K3s and RKE2
- If elemental-ui >` 1.0.0`, UI is different than before
- OS image upgrade is tested if the cluster type is K3s, 
- Os version channel upgrade is tested if the cluster type is RKE2
[UI-RKE2-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4314521676/jobs/7527682726) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4314520729/jobs/7527682292) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Latest ](https://github.com/rancher/elemental/actions/runs/4314522401/jobs/7527684173) ❌ - not related to the PR (Rancher bug) …
=> ci/ui: add test to upgrade via os version channel

tests/scripts/install-vm
This PR contains 2 commits:
- reserve 24GB of RAM for Rancher Manager instead of 12GB, as with more that 10 nodes we can see OOM killer errors
- make the use of hugepages optional: as if we add more nodes more memory seems to be needed on Rancher Nabager side (this should be debugged later)
Related to #655.
- [OBS-Stable-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4322882661/jobs/7545846626)
**NOTE:** the VR is failing because of #667.
=> ci/e2e: fix/reduce OOM killer issue in CI with lot of nodes

.github/workflows/master-e2e.yaml, tests/e2e/bootstrap_test.go
Emulated TPM should be used if set to true.
We can see that Emulated TPM is not used in this [test](https://github.com/rancher/elemental/actions/runs/4338278640/jobs/7574869063) even if `EMULATE_TPM: true` is set:
```
STEP: Setting emulated TPM to false @ 03/05/23 22:26:08.494
```
Verification run (it fails for another issue):
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4345339110)
=> ci/e2e: fix emulated TPM

tests/cypress/e2e/unit_tests/machine_inventory.spec.ts, tests/cypress/e2e/unit_tests/machine_registration.spec.ts, tests/cypress/fixtures/custom_cloud-config.yaml, tests/cypress/support/e2e.ts, tests/cypress/support/functions.ts
Fix #676 
We test two things in this new test:
- Add hardware labels in Machine Registration and make sure we can see them inside YAML
- Check we can also see them in machine inventoy after booting a node
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4346381195) :heavy_check_mark:
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4348068771) :heavy_check_mark: 
Configure label and check inside Machine registration test (**from 8:13 to the end**):
https://user-images.githubusercontent.com/6025636/223232322-7e6932d1-f6e5-4c2e-8b83-a011f036ef59.mp4
Machine inventory check (**from 0:20 to 1:30**)
https://user-images.githubusercontent.com/6025636/223231675-6dd8ca0a-db69-497b-9361-ee3bb1f87073.mp4
=> ci/ui: Test embedded hardware labels

tests/cypress/support/functions.ts
Fix #714 
Workaround for https://github.com/rancher/elemental/issues/714
* Delete all resources instead of selecting one by name
https://github.com/rancher/elemental/actions/runs/4354615339
=> ci/ui: Workaround in delete machine reg test

.github/workflows/master-e2e.yaml, tests/assets/configure-gh-runner.sh, tests/e2e/bootstrap_test.go
Multiple changes to improve scalability tests:
- Use LVM with striping I/O for local storage, this will improve I/O performance for bootstrapping nodes when multiples local SSDs are used (which is the case for highmem runner).
- Bootstrap additional nodes with ISO and use PXE to bootstrap the master ones.
- Wait a little bit before rebooting the nodes, this is to avoid starting all VMs at the same time.
- [OBS-Stable-RKE2-E2E with 30 nodes](https://github.com/rancher/elemental/actions/runs/4365471173)
- [OBS-Stable-RKE2-E2E with 50 nodes](https://github.com/rancher/elemental/actions/runs/4375907053)
**NOTE:** VR with 50 nodes is failing because of issue #667, not related to this PR.
=> ci/e2e: multiple changes to improve scalability tests

.github/workflows/cli-obs-manual-workflow.yaml
This allows anyone to manually trigger a test on any version of Elemental ISO/operator/kubernetes client cluster.
Default is set to OBS-Dev on K3s.
=> ci: add worflow to manually trigger a test

.obs/specfile/elemental.spec, framework/files/system/oem/05_motd_and_autologin.yaml, framework/files/system/oem/99_elemental-register.yaml, framework/files/usr/lib/systemd/system/elemental-register.service
=> Run elemental-register in systemd service

framework/files/usr/lib/systemd/system/elemental-system-agent.service
This is to allow further custom settings for the `elemental-system-agent.service`. Basically it copies the options from `rancher-system-agent.service` created during k3s of rke2 provisioning.
=> Add environment variable files in elemental-system-agent.service

tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
With latest rancher manager `2.7.2-rc6`, there is something different regarding cluster status  when you create a cluster.
Looks like the status before `Updating` (`Reconciling` / `Provisioning`) are longer.
Actually, we do not want to test each status, we want an `Active` cluster after all.
[K3s-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4424444178/jobs/7758829555)
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4424697891/jobs/7758851825)
=> ci/ui: increase timeout when checking cluster

tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts, tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Fix #741 
[RKE2-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4446200296) :heavy_check_mark: 
[UI-RKE2-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4446179234) :heavy_check_mark:
=> ui/ci: increase timeout when creating RKE2 cluster

.github/workflows/cli-obs-manual-workflow.yaml, tests/Makefile, tests/e2e/bootstrap_test.go, tests/e2e/suite_test.go, tests/scripts/install-vm
This fix #734.
- [CLI-OBS-Manual-Workflow  with 50 nodes](https://github.com/rancher/elemental/actions/runs/4429384060)
- [CLI-OBS-Manual-Workflow  with 100 nodes](https://github.com/rancher/elemental/actions/runs/4430742731)
- [CLI-OBS-Manual-Workflow  with 80 nodes](https://github.com/rancher/elemental/actions/runs/4437077202/) 
- [CLI-OBS-Manual-Workflow  with 160 nodes](https://github.com/rancher/elemental/actions/runs/4439953126)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4446071247)
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4446108604)
- [K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4446121424)
Latest VRs after creating `waitNodesBoot` function:
- …
=> ci/e2e: delay nodes boot to reduce CPU and I/O load

.github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/cli-k3s-sequential-rancher_latest.yaml, .github/workflows/e2e-k3s-latest.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-e2e-k3s-latest.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
Will fix https://github.com/rancher/rancher/issues/40679
[UI-K3s-OS-Upgrade-Rancher_Latest ](https://github.com/rancher/elemental/actions/runs/4446398743) :heavy_check_mark: 
[K3s-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4448136663) ❌ (not related to k3s, elemental-ui was bumped in the same time (1.2.0)
[CLI-K3s-Sequential-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4448114226) :heavy_check_mark: 
[CLI-K3s-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4448112985) :heavy_check_mark: 
[K3s-E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4448112991l) :heavy_check_mark:
=> ci: bump k3s to v1.24.11+k3s1

tests/e2e/configure_test.go
Hardened cluster test fails since 5 days in a row.
https://github.com/rancher/elemental/actions/runs/4464004969/jobs/7839756974
`  In [It] at: /home/gh-runner/actions-runner/_work/elemental/elemental/tests/e2e/configure_test.go:177 @ 03/20/23 02:19:26.06`
It looks like an issue with network creation, I need to manually trigger the test and figure out what happens there.
Add wait between virsh commands.
1- https://github.com/rancher/elemental/actions/runs/4470203781/jobs/7853419414?pr=748 :heavy_check_mark: 
2- https://github.com/rancher/elemental/actions/runs/4470203781/jobs/7855078487 :heavy_check_mark: 
3- https://github.com/rancher/elemental/actions/runs/4470203781/jobs/7855595677 :heavy_check_mark: 
4- https://github.com/rancher/elemental/actions/runs/4470203781/jobs/7857732128 …
=> ci: debug hardened cluster issue

framework/files/etc/cos/bootargs.cfg, framework/files/system/oem/01_elemental-rootfs.yaml
This commit drops the expansion cloud-init step for COS_PERSISTENT partition. The installation already uses all available size by default there is not need to attempt a resize on every boot.
In addition this commit also updates the persistent volumes configuration to be aligned with the latest elemental-toolkit changes. Now volumes are set as part of the kernel arguments at boot and not as part of the cloud-init setup. This prevents including filesystem label literals within the immutable OS.
Related to #732
=> Do not expand COS_PERSISTENT by default

.github/workflows/cli-k3s-hardened-rancher_latest.yaml, .github/workflows/cli-k3s-hardened-rancher_stable.yaml, README.md
- Test hardened cluster with latest Rancher Manager (this case was missing)
- Add status badges in the README
[CLI-K3s-Hardened-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4479456183) :heavy_check_mark:
=> ci: Improve tests on hardened cluster

.github/workflows/master-e2e.yaml, tests/Makefile, tests/assets/dumb_machineRegistration.yaml, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/e2e/uninstall-operator_test.go
Check that Elemental Operator can be delete and reinstall after. Also check that non-elemental resources can still be deleted/created.
Should fix https://github.com/rancher/elemental-operator/issues/314.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4499484550)
- [OBS-Dev-RKE-E2E](https://github.com/rancher/elemental/actions/runs/4499493942)
- [K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4499502065)
=> ci/e2e: add operator uninstall test

.github/workflows/master-e2e.yaml
Only Elemental Operator version v1.1.5 or above is supported.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4530024786)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4530030016)
- [K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4530037473)
- [CLI-K3s-OS-Upgrade](https://github.com/rancher/elemental/actions/runs/4530041345)
=> ci/e2e: don't test operator uninstallation on Stable

.github/workflows/master-e2e.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts, tests/cypress/latest/support/e2e.ts, tests/cypress/latest/support/functions.ts, tests/e2e/ui_test.go, tests/scripts/start-cypress-tests
Fix #578 
At the time of writing, we can only build an ISO based on the stable ISO, that means the best place to test it is in the upgrade test before in that one, we start from STABLE ISO and upgrade to DEV ISO.
Later on, when we will be able to select building from DEV ISO, the test could be moved to the main scenario.
- [UI-K3s-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4515878010)
it booted perfectly with ISO built in the UI:
```
+ ln -s /home/gh-runner/actions-runner/_work/elemental/elemental/elemental-from-cypress.iso node-001/
+ INSTALL_FLAG+=' --cdrom node-001/elemental-from-cypress.iso'
```
- [UI-RKE2-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4519482195)
Same comment as above.
Check if it does not break tests …
=> ci/ui: test ISO building feature

tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Fix #737 
New test to make sure a cluster cannot be bound to two upgrade groups.
[UI-K3s-OS-Upgrade-Rancher_Latest ](https://github.com/rancher/elemental/actions/runs/4534063054 ):clock1: 
[UI-RKE2-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4534065565) :clock1:
=> e2e/ui: Make sure we can bind a cluster to only one upgrade group at a time

tests/e2e/helpers/misc/misc.go
We need to add `protect-kernel-defaults` value to be able to install applications from the UI.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4568394875)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4568392768)
I manually validated that I was able to install an application through the Rancher UI.
=> ci/e2e: fix Cluster structure

tests/e2e/bootstrap_test.go
This should fix this [sporadic issue](https://github.com/rancher/elemental/actions/runs/4592090596/jobs/8110878318).
- [CLI-OBS-Manual-Workflow](https://github.com/rancher/elemental/actions/runs/4594685995) with K3s and sequential bootstrapping
- [CLI-OBS-Manual-Workflow](https://github.com/rancher/elemental/actions/runs/4595302245) with RKE2 and parallel bootstrapping
- [K3s-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4594918575)
=> ci/e2e: fix sporadic kubectl version issue

tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts, tests/cypress/latest/fixtures/machine_inventory_1.yaml
Fix #653 
Verification run: https://github.com/rancher/elemental/actions/runs/4627421933 :clock1: 
Regression test for https://github.com/rancher/elemental/issues/627
Now it tests with lowercase + lower/uppercase:
=> ci/ui: test filtering with lower and upper case

.github/workflows/ui-e2e-k3s-stable.yaml, .github/workflows/ui-e2e-rke2-stable.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts, tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts, tests/cypress/latest/support/elemental.ts
Fix #782 
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4676694270) :heavy_check_mark: 
[RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4676710824) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4676712327) ❌
[UI-RKE2-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4676713448) ❌
Upgrade tests don't work but that's expected because operator stable is still the old one, so it is not compatible with `RM 2.7.2` and `elemental-ui 1.2`. There will pass once next stable released.
`elemental_ui_version` variable will be completely removed later, when we will remove the `cypress/1.0.0` folder.
=> ci/ui: adapt to rancher 2.7.2 (latest stable)

.github/workflows/cli-obs-manual-workflow.yaml, .github/workflows/e2e-k3s-obs-Dev.yaml, .github/workflows/e2e-k3s-obs-Stable.yaml, .github/workflows/e2e-k3s-obs-Staging.yaml, .github/workflows/master-e2e.yaml
Needed to run E2E during release validation.
- TO_BE_DONE
=> ci/e2e: add cluster_type option to OBS tests

.github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/cli-k3s-os-upgrade.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/cli-rke2-os-upgrade.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade.yaml
Use the new path to provide the OS channel list.
This should fix this [issue](https://github.com/rancher/elemental/actions/runs/4716820990).
- [CLI-K3s-OS-Upgrade](https://github.com/rancher/elemental/actions/runs/4719418033)
=> ci: fix upgrade channel

.github/workflows/master-e2e.yaml
The default version of backup-restore-operator is enough for Elemental now.
This commit also adds an input to be able to force the version if needed.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4734477318)
=> ci/e2e: use default version of backup-restore-operator

tests/Makefile, tests/e2e/backup-restore_test.go
Installation of backup/restore operator should be done right after Rancher Manager.
- [OBS-Stable-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4743442874)
=> ci/e2e: split backup/restore test

.github/workflows/master-e2e.yaml, .github/workflows/ui-e2e-k3s-latest.yaml, .github/workflows/ui-e2e-k3s-obs-Dev.yaml, .github/workflows/ui-e2e-k3s-obs-Stable.yaml, .github/workflows/ui-e2e-k3s-obs-Staging.yaml, .github/workflows/ui-e2e-k3s-stable.yaml, .github/workflows/ui-e2e-rke2-latest.yaml, .github/workflows/ui-e2e-rke2-obs-Dev.yaml, .github/workflows/ui-e2e-rke2-obs-Stable.yaml, .github/workflows/ui-e2e-rke2-obs-Staging.yaml, .github/workflows/ui-e2e-rke2-stable.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade.yaml, tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts, tests/scripts/start-cypress-tests
Fix #799 
[OBS-Stable-K3s-UI_E2E-with-stable-UI](https://github.com/rancher/elemental/actions/runs/4763106258) :heavy_check_mark: 
Non-regression test:
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4763101300) :heavy_check_mark:
=> ci/ui: ability to install ui from official chart

framework/files/usr/sbin/suc-upgrade
Unless force-flag applied, this commit ensures upgrades running on the node are only executed if booted into active-mode.
Fixes #708
=> Only allow upgrades on active system

tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts, tests/cypress/latest/support/functions.ts, tests/scripts/start-cypress-tests
- Fix #812 
- Fix also that elemental ISO is now named with registration endpotin name + timestamp and not only elemental.iso anymore
- Change how we check if a node is rebooted when upgrading it
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4819952997) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4819955724) :heavy_check_mark: 
[UI-RKE2-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4819956943):heavy_check_mark:
[UI-RKE2-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4819958319) :heavy_check_mark:
=> 812 several fixes for upgrade tests

.github/workflows/cli-rke2-scalability-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-rancher_latest.yaml, .github/workflows/ui-k3s-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-rancher_latest.yaml, .github/workflows/ui-rke2-rancher_stable.yaml
Useful for debugging when it fails.
- [CLI-RKE2-Scalability-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4828849696) - with `destroy_runner` set to `false`
- [UI-K3s-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4829078181) - with `destroy_runner` set to `true`
- [UI-RKE2-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4829086480) - with `destroy_runner` set to `false`
=> ci/e2e: add option to keep runner in scalability test

.github/workflows/cli-rke2-scalability-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-rancher_latest.yaml, .github/workflows/ui-k3s-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-rancher_latest.yaml, .github/workflows/ui-rke2-rancher_stable.yaml
Reverts rancher/elemental#817
CI broken by this PR, let's revert it.
=> Revert "ci/e2e: add option to keep runner in scalability test"

framework/files/system/oem/01_elemental-rootfs.yaml
We are suffering from a small yip regression. Since v1.0.0 yip uses a DAG (Directed Acyclic Graph) to _sort_ and relate all the required executions, allowing parallel executions (we have not played with it so far). However one of the side effects is that the dag structures items in a map internally using the step name if provided, hence having two steps with the same name causes the step overwrite.
Exactly this is what is happening in the layout setup, we have two steps for that (recovery and non recovery) with the same name, so one of the two gets ignored...
Fixes #829
=> Ensure names are unique for all stages

framework/files/system/oem/02_datasources.yaml
If cloud-init data is provided as the `user-data` file in an eligible device this data is copied to both `/oem/userdata.yaml` and `/oem/userdata`. Since `/oem` is an analyzed path for custom cloud-init files this will be taken into accound on later `elemental run-stage` calls.
=> Enable cloud-config from removable devices

.github/workflows/cli-k3s-hardened-rancher_latest.yaml, .github/workflows/cli-k3s-hardened-rancher_stable.yaml, .github/workflows/cli-k3s-obs_dev.yaml, .github/workflows/cli-k3s-obs_stable.yaml, .github/workflows/cli-k3s-obs_staging.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, tests/Makefile, tests/e2e/install_test.go, tests/e2e/suite_test.go
Fix #830 
[UI-RKE2-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4989183710) :heavy_check_mark: 
[UI-RKE2-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4989576107) ❌ - issue not related to this PR.
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4989185301) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Latest ](https://github.com/rancher/elemental/actions/runs/4989186096) :heavy_check_mark: 
[UI-K3s-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4989186998) :heavy_check_mark: 
[UI-RKE2-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4989188001) :heavy_check_mark: 
[CLI-K3s-OBS_Dev](https://github.com/rancher/elemental/actions/runs/4989866835) …
=> ci: configure RKE2 as management node for UI upgrade tests ( RKE2)

.github/workflows/master-e2e.yaml, .github/workflows/ui-rke2-obs_dev.yaml, .github/workflows/ui-rke2-obs_stable.yaml, .github/workflows/ui-rke2-obs_staging.yaml, .github/workflows/ui-rke2-os-upgrade.yaml, .github/workflows/ui-rke2-rancher_latest.yaml, .github/workflows/ui-rke2-rancher_stable.yaml, tests/cypress/latest/e2e/unit_tests/seed_image.spec.ts, tests/cypress/latest/fixtures/myseedimage.yaml, tests/cypress/latest/plugins/index.ts, tests/scripts/start-cypress-tests
Second part of https://github.com/rancher/elemental/issues/648
[UI-RKE2-OBS_Dev](https://github.com/rancher/elemental/actions/runs/5003093027) :heavy_check_mark: 
[UI-RKE2-OBS_Stable](https://github.com/rancher/elemental/actions/runs/5003093868) ❌ (not related to this PR, rancher 2.7.5-rc1)
[UI-RKE2-OBS_Staging](https://github.com/rancher/elemental/actions/runs/5003950318) :clock1: 
[UI-RKE2-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/5003095047) :heavy_check_mark: 
[UI-RKE2-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/5003104304) :heavy_check_mark: 
[UI-K3s-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/5003680585) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/run …
=> ci/ui: use RKE2 as upstream cluster for all RKE2 UI tests

.github/workflows/cli-k3s-obs_dev.yaml, .github/workflows/cli-k3s-obs_stable.yaml, .github/workflows/cli-k3s-obs_staging.yaml, .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml, .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/cli-k3s-os-upgrade.yaml, .github/workflows/cli-obs-manual-workflow.yaml, .github/workflows/cli-rke2-obs_dev.yaml, .github/workflows/cli-rke2-obs_stable.yaml, .github/workflows/cli-rke2-obs_staging.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml, .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/cli-rke2-os-upgrade.yaml, .github/workflows/master-e2e.yaml, .github/workflows/ui-k3s-obs_dev.yaml, .github/workflows/ui-k3s-obs_stable.yaml, .github/workflows/ui-k3s-obs_staging.yaml, .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml, .github/workflows/ui-k3s-os-upgrade.yaml, .github/workflows/ui-rke2-obs_dev.yaml, .github/workflows/ui-rke2-obs_stable.yaml, .github/workflows/ui-rke2-obs_staging.yaml, .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml, .github/workflows/ui-rke2-os-upgrade.yaml, tests/e2e/install_test.go, tests/e2e/suite_test.go, tests/e2e/uninstall-operator_test.go, tests/e2e/upgrade_test.go
Elemental Operator chart has been split, so newer versions should install all charts.
- [CLI-K3s-OBS_Dev](https://github.com/rancher/elemental/actions/runs/5092311471)
- [UI-K3s-OBS_Dev](https://github.com/rancher/elemental/actions/runs/5091386989)
- [UI-K3s-OBS_Stable](https://github.com/rancher/elemental/actions/runs/5091802366)
=> ci: install CRDs chart for operator when needed
