rancher/elemental

- pkg/config/config.go
- pkg/config/read.go
- pkg/config/read_test.go
- tests/smoke/smoke_test.go
- tests/sut/sut.go
> Add containerImages as source

- docs/installation.md
`config_url` should be used instead of `configurl`.
> docs: fix installation

- cmd/ros-installer/main.go
- pkg/config/config.go
- pkg/install/install.go
> Add reboot flag

- ros-image-build
Follow-up: https://github.com/rancher-sandbox/cOS-toolkit/issues/1148
> Add mtools to ros-image-build image

- .github/workflows/docs.yaml
- docs/architecture.md
- docs/dashboard.md
- docs/upgrade.md
- mkdocs.yml
> Fix docs and link ot operator docs

- Dockerfile
- tests/scripts/configure-rancher-step-01
> Allow configuring chart url/version

- .github/workflows/install-with-rancher.yaml
Only when a PR is merged on `master` branch.
I also added my GH runner with label `nested-virt` to be able to run this test as a workaround, until being able to fix my cirrus-ci run.
> Schedule bootstrapping test

- ros-image-build
> Remove manifest.yaml file to build ISO and relay on defaults

- go.mod
- go.sum
- pkg/config/read.go
> Append systemCA when using self-signed certs

- docs/architecture.md
- docs/customizing.md
- docs/installation.md
- docs/upgrade.md
- mkdocs.yml
Drop all references to "RancherOS2", "os2", or "rancher-sandbox".
> Rename from os2 in docs

- .github/workflows/e2e-tests.yaml
- tests/assets/net-default.xml
- tests/e2e/README.md
- tests/e2e/upgrade_test.go
Should fix https://github.com/rancher/elemental/issues/43.
TODO:
> ci/e2e: add manual upgrade test

- framework/files/system/oem/01_ros-rootfs.yaml
> Ensure /usr/local/bin exists on COS_PERSISTENT

- .github/workflows/build-iso.yaml
Tested here: https://github.com/ldevulder/gha-tests/actions/runs/2710796777
> ci: better to use actions-setup-docker to install docker

- Makefile
Blocked until https://github.com/rancher/elemental-cli/pull/289
> Use new elemental-cli repo

- framework/files/system/oem/99_elemental-operator.yaml
> Add elemental install logs in journal

- docs/ami.md
- docs/clusters.md
- docs/installation.md
- mkdocs.yml
> Minor doc fixes

- framework/files/usr/lib/systemd/system/elemental-system-agent.service
Also enable debug mode by default in the agent so we can see whats going
on
> Fix agent dir

- Dockerfile.image
Otherwise we get failures when we source the file
> Enable quotes on /etc/os-release

- Dockerfile.image
- Makefile
> track latest elemental-cli version published

- .github/workflows/build-ci.yaml
> Run the build-ci job nigthly

- elemental-iso-build
> Small improvements to the info generated via the build iso script

- docs/quickstart.md
- examples/quickstart/cluster.yaml
- examples/quickstart/registration.yaml
- examples/quickstart/selector.yaml
- mkdocs.yml
> Add quickstart

- framework/files/system/oem/99_elemental_system_agent.yaml
> Fix elemental system agent config

- framework/files/usr/sbin/suc-upgrade
Fixes https://github.com/orgs/rancher/projects/9
> Update deprecated upgrade option

- docs/quickstart.md
Clarify server-url requirement.
Clarify choosing k8s versions + link to matrix
From feedback on the quickstart guide
> Expand quickstart docs

- docs/elemental-plans.md
- mkdocs.yml
> Add plans doc

- .github/workflows/build-ci.yaml
- .github/workflows/build-iso.yaml
- .github/workflows/docs.yaml
- .github/workflows/e2e.yaml
- .github/workflows/image.yaml
- docs/quickstart.md
- elemental-iso-build
- mkdocs.yml
Part of https://github.com/rancher/elemental-toolkit/issues/156
> Rename master to main

- .github/workflows/build-iso.yaml
- elemental-iso-build
> Add some basic checks to iso generated by elemental-iso-build

- docs/cloud-config-reference.md
- docs/kubernetesversions.md
- docs/machineregistration-reference.md
Nothing huge but i like standardized things :smile: 
Before:
After:
> Make section titles uniform

- docs/quickstart.md
- docs/tpm.md
- examples/quickstart/registration-tpm.yaml
Fixes https://github.com/rancher/elemental/issues/243
> [docs] Add example how to add TPM emulation for bare metal

- docs/machineregistration-reference.md
- docs/smbios.md
- examples/quickstart/registration.yaml
- mkdocs.yml
> docs: Add smbios docs

- docs/machineregistration-reference.md
- docs/smbios.md
update also the machineName to the new default
> docs: add config:elemental:registration section

- .github/workflows/ui-e2e.yaml
- cypress.json
- cypress/integration/unit_tests/machine_inventory.spec.ts
- cypress/integration/unit_tests/machine_registration.spec.ts
- cypress/plugins/index.ts
- scripts/start_cypress_tests.sh
- tests/Makefile
- tests/e2e/ui_test.go
Fix #295 
As Machine Registration tests are done, now we need to deploy a node and check that it appears in the Elemental UI in Machine Inventory.
https://github.com/rancher/elemental/actions/runs/3014527774
> Bootstrap a node to join UI (Cypress)

- .github/workflows/e2e.yaml
- tests/assets/emulated_tpm.yaml
- tests/e2e/bootstrap_test.go
- tests/e2e/configure_test.go
- tests/e2e/suite_test.go
- tests/scripts/install-vm
Should fix https://github.com/rancher/elemental/issues/291.
These PR needs to be merged before:
- https://github.com/rancher/elemental-operator/pull/169
- https://github.com/rancher/elemental-operator/pull/170
- https://github.com/rancher/elemental-operator/pull/171
Verification run: https://github.com/ldevulder/elemental/runs/8267439630
> ci/e2e: add TPM emulation test

- Dockerfile.image
This could be useful for debugging purposes
> Add elemental-support binary in generated image

- framework/files/system/oem/99_networking.yaml
> Enable networkmanager

- .github/workflows/ui-e2e.yaml
- cypress.json
- cypress/integration/unit_tests/machine_selector.spec.ts
- cypress/support/elemental.ts
- tests/assets/machineregistration.yaml
Fix #314 
https://github.com/rancher/elemental/actions/runs/3066670197/jobs/4952105560 :heavy_check_mark:
> Add machine selector Cypress tests

- .github/elemental-iso-build
- Makefile
> Run build-iso in non privileged containers

- .github/workflows/release.yaml
> Add elemental-iso-build to release pipeline

- Dockerfile.image
> Remove syslinux addition, it is part of the base image now

- Makefile
- tests/Makefile
- tests/install/install_test.go
> Use EFI firmware for CI

- cypress/integration/unit_tests/upgrade.spec.ts
- package.json
Fix #357 
Verification run: https://github.com/rancher/elemental/actions/runs/3130090701/jobs/5079946250
> Add Cypress tests to check OS versions channels

- .github/workflows/e2e.yaml
- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
Should fix https://github.com/rancher/elemental/issues/336.
> ci/e2e: use new self-hosted runner

- .github/workflows/e2e.yaml
- .github/workflows/master-e2e.yaml
Tested here: https://github.com/ldevulder/gha-tests/actions/runs/3142808653
> ci/e2e: secret shouldn't be directly configured in master

- tests/e2e/bootstrap_test.go
- tests/scripts/install-vm
This PR also fix an issue with `ipxe.efi` link.
> Fix flacky E2E test

- .github/workflows/e2e.yaml
- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e.yaml
Try to really fix it this time...
> ci/e2e+ui: set condition to start the runner #2

- .github/workflows/master-e2e.yaml
- tests/assets/net-default.xml
Asked by Paul ;-)
**Note:** I'm not sure that the runner is powerful enough to handle 5 nodes, but it can be easily increased. So let's see how the first run with 5 nodes goes.
> ci/e2e: increase test to 5 nodes

- .obs/workflows.yml
> Include OBS workflow for Dev and Staging packages update in OBS

- docs/architecture.md
- mkdocs.yml
> docs: rework the Architecture section

- .github/workflows/e2e.yaml
- .github/workflows/master-e2e.yaml
- tests/assets/cluster.yaml
- tests/e2e/README.md
- tests/e2e/bootstrap_test.go
- tests/e2e/install_test.go
- tests/scripts/install-vm
- 1st run: https://github.com/ldevulder/elemental/actions/runs/3251894449
- 2nd run: https://github.com/ldevulder/elemental/actions/runs/3254671672
- 3rd run: https://github.com/ldevulder/elemental/actions/runs/3255058555
> ci/e2e: try to fix sporadic issues

- docs/machineregistration-reference.md
> docs: add default values for machineregistration reference

- .github/workflows/e2e-obs-Dev.yaml
- .github/workflows/e2e-obs-Staging.yaml
- .github/workflows/e2e.yaml
- .github/workflows/master-e2e.yaml
- tests/e2e/bootstrap_test.go
- tests/e2e/install_test.go
- tests/e2e/suite_test.go
- tests/e2e/upgrade_test.go
Verification run: https://github.com/ldevulder/elemental/actions/runs/3266173805
> e2e: add option to select Rancher Manager version and Teal ISO to test

- .github/workflows/e2e.yaml
Should fix this issue: https://github.com/rancher/elemental/actions/runs/3266797237/jobs/5371069900, which was introduced by PR https://github.com/rancher/elemental/pull/426.
Verification run: https://github.com/ldevulder/elemental/actions/runs/3267658765.
> ci/e2e: fix issue with stable/latest

- docs/customizing.md
> Improving customization docs

- docs/quickstart.md
We now have the 'staging' repo which builds elemental images when we tag (release) the elemental-operator repo: update the links.
> docs: update links

- .github/elemental-iso-add-registration
- docs/quickstart.md
> Move staging links to stable

- docs/elementaloperatorchart-reference.md
- docs/machineinventoryselectortemplate-reference.md
- docs/machineregistration-reference.md
Fix some minor typos.
Fixes: #456
> docs: small changes to reference section

- docs/installation.md
- docs/upgrade.md
> docs: some little improvements on installation docs

- docs/architecture.md
- mkdocs.yml
Few typos and small reworks.
Fixes #454
> docs: update Architecture section

- .github/elemental-iso-add-registration
- .github/workflows/build-iso-inject-pr.yaml
> Fix injection iso script under darwin

- docs/restore.md
- mkdocs.yml
Fixes https://github.com/rancher/elemental/issues/447
> Add procedure howto restore elemental CRD resources

- .github/workflows/build-iso-inject-pr.yaml
- .github/workflows/build-iso-pr.yaml
- .github/workflows/build-iso.yaml
- .github/workflows/image.yaml
> ci: Fix github deprecations

- docs/restore.md
- scripts/rancher-agent-token-update
Fixes https://github.com/rancher/elemental/issues/447
> Add warning to restore procedure about rancher-system-agent

- .github/workflows/docs.yaml
- yarn.lock
Only push on main branch, when files are changed.
On PR, always rebuild
Fixes https://github.com/rancher/elemental/issues/496
> Run docs on PR

- .github/workflows/docs.yaml
Signed-off-by: itxaka <igarcia@suse.com>
> ci: Bump action and use yarn.lock for cache

- docs/upgrade.md
Not sure where the link should point, but hopefully this is correct :+1: 
> docs: Use variables for operator name

- docusaurus.config.js
> Add a 'Slack' link next to 'GitHub'

- docs/backup.md
Just a small addition to help user during backup configuration.
> docs: small improvment in backup

- examples/upgrade/upgrade-cluster-target.yaml
- examples/upgrade/upgrade-node-selector.yaml
...like SLE Micro for Rancher 5.2
> don't reference outdated image projects

- .github/workflows/ui-e2e.yaml
- cypress/e2e/unit_tests/machine_registration.spec.ts
- cypress/support/functions.ts
Fix #540 
Before:
After:
https://github.com/rancher/elemental/actions/runs/3573077889/jobs/6006727745
The failure is related to the upgrade issue, nothing linked to this PR.
> Small fixes to match elemental-ui 0.1.4

- docs/quickstart.md
Signed-off-by: Simon Flood <simonflood@users.noreply.github.com>
> Fixed typos in quickstart.md

- .github/workflows/build-ci.yaml
- .github/workflows/e2e-rke2-obs-Dev.yaml
- .github/workflows/e2e-rke2-obs-Stable.yaml
- .github/workflows/e2e-rke2-obs-Staging.yaml
- .github/workflows/integration.yaml
- .github/workflows/master-e2e.yaml
Add 3 missing files and rename `key:` variable.
> Fix E2E tests

- .github/workflows/master-e2e.yaml
> ci/e2e: fix path for artifacts

- .github/workflows/master-e2e.yaml
Add more information in the CI summary.
Verification Run: https://github.com/rancher/elemental/actions/runs/3622555870
> ci/e2e: add elemental-operator version in summary

- .github/workflows/ui-e2e-k3s.yaml
This should fix this issue: https://github.com/rancher/elemental/actions/runs/3626461866/jobs/6115479156
> ci/ui: fix empty variables in scheduled test

- .github/workflows/ui-e2e-rke2.yaml
Forgot to fix it in RKE2 test as well...
> ci/ui: fix empty variables in scheduled test - part 2

- .github/workflows/master-e2e.yaml
- cypress/e2e/unit_tests/upgrade.spec.ts
- cypress/plugins/index.ts
- tests/scripts/start_cypress_tests.sh
Fix #569
VR with stable operator (1.0.x): https://github.com/rancher/elemental/actions/runs/3647457009
Test failed for another reason not related to this PR.
VR with dev operator: https://github.com/rancher/elemental/actions/runs/3647453022
> Remove syncInterval if operator vers is 1.0 (UI)

- Dockerfile.image
- framework/files/usr/lib/systemd/system/elemental-system-agent.service
> Depend elemental system agent on synced time

- cypress/support/functions.ts
Fix #571 
Verification Run:
https://github.com/rancher/elemental/actions/runs/3683612598
> Increase timeout to delete a resource with Cypress

- .obs/dockerfile/_constraints
- .obs/specfile/elemental-rpmlintrc
> Include the rpmlintrc file within the spec file

- .obs/workflows.yml
> Include image services trigger on rancher/elemental changes

- .github/workflows/master-e2e.yaml
- cypress/e2e/unit_tests/deploy_app.spec.ts
Fix #588 
Verification run: :checkered_flag: 
https://github.com/rancher/elemental/actions/runs/3748671122
> Deploy sample app through UI in Elemental cluster

- .github/workflows/e2e-k3s-obs-Dev.yaml
- .github/workflows/e2e-k3s-obs-Stable.yaml
- .github/workflows/e2e-k3s-obs-Staging.yaml
- .github/workflows/ui-e2e-k3s-obs-Dev.yaml
- .github/workflows/ui-e2e-k3s-obs-Stable.yaml
- .github/workflows/ui-e2e-k3s-obs-Staging.yaml
In the previous [PR](https://github.com/rancher/elemental/pull/594), I updated the wrong files...
> Configure proxy in UI tests only

- .obs/dockerfile/Dockerfile
> Install kernel-firmware-all package

- Dockerfile.image
- framework/files/etc/cos/bootargs.cfg
- framework/files/usr/sbin/self-upgrade
- framework/files/usr/sbin/suc-upgrade
> Add debug flag on upgrade command and update bootargs.cfg file

- tests/e2e/bootstrap_test.go
- tests/scripts/install-vm
This will increase performance when lot of nodes are used.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/3994221762)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/3995151492)
> ci/e2e: use hugepages for VM

- .obs/specfile/elemental.spec
Adding the service to %pre, %post, %preun and %postun
> Add shutdown-k3s.service to OBS spec

- .github/workflows/master-e2e.yaml
- Dockerfile.image
> Remove cloud-config/upgrade_grub_hook package

- .obs/workflows.yml
Based on the feedback from https://github.com/openSUSE/open-build-service/issues/13206#issuecomment-1429857569 this fixes https://github.com/rancher/elemental/issues/522
> Remove branch filter on OBS workflow for tag events

- .github/workflows/image.yaml
> Update docker/login-action to v2.1.0

- .github/workflows/master-e2e.yaml
- .github/workflows/ui-e2e-k3s-latest.yaml
- .github/workflows/ui-e2e-k3s-obs-Dev.yaml
- .github/workflows/ui-e2e-k3s-obs-Stable.yaml
- .github/workflows/ui-e2e-k3s-obs-Staging.yaml
- .github/workflows/ui-e2e-k3s-stable.yaml
- .github/workflows/ui-e2e-rke2-latest.yaml
- .github/workflows/ui-e2e-rke2-obs-Dev.yaml
- .github/workflows/ui-e2e-rke2-obs-Stable.yaml
- .github/workflows/ui-e2e-rke2-obs-Staging.yaml
- .github/workflows/ui-e2e-rke2-stable.yaml
- tests/cypress/e2e/unit_tests/advanced_filtering.spec.ts
- tests/cypress/e2e/unit_tests/deploy_app.spec.ts
- tests/cypress/e2e/unit_tests/elemental_plugin.spec.ts
- tests/cypress/e2e/unit_tests/first_connection.spec.ts
- tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
- tests/cypress/e2e/unit_tests/machine_registration.spec.ts
- tests/cypress/e2e/unit_tests/machine_selector.spec.ts
- tests/cypress/e2e/unit_tests/menu.spec.ts
- tests/cypress/e2e/unit_tests/upgrade.spec.ts
- tests/cypress/e2e/unit_tests/user.spec.ts
- tests/cypress/plugins/index.ts
- tests/cypress/support/filterTests.js
- tests/scripts/start-cypress-tests
Fix #680 
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4225773365) :heavy_check_mark: 
[K3s-UI_E2E-Latest_RM](https://github.com/rancher/elemental/actions/runs/4224597044) :heavy_check_mark:
> ci/ui: add label functionality to Cypress tests

- tests/cypress/e2e/unit_tests/advanced_filtering.spec.ts
- tests/cypress/e2e/unit_tests/deploy_app.spec.ts
- tests/cypress/e2e/unit_tests/elemental_plugin.spec.ts
- tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
- tests/cypress/e2e/unit_tests/machine_registration.spec.ts
- tests/cypress/e2e/unit_tests/machine_selector.spec.ts
- tests/cypress/e2e/unit_tests/menu.spec.ts
- tests/cypress/e2e/unit_tests/upgrade.spec.ts
- tests/cypress/e2e/unit_tests/user.spec.ts
- tests/cypress/plugins/index.ts
- tests/cypress/support/e2e.ts
- tests/cypress/support/elemental.ts
- tests/cypress/support/filterTests.js
- tests/cypress/support/functions.ts
I have wanted to improve the Cypress code for a long time, like consistent in variable names etc
[K3s-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4324765877/jobs/7550038910) :heavy_check_mark: 
[RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4324764311) :clock1: 
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4324759776/jobs/7550031786) :heavy_check_mark: 
[UI-RKE2-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4324761377/jobs/7550028796) :heavy_check_mark:
> ci/ui: improve code style

- .obs/dockerfile/Dockerfile
> Include cryptsetup in elemental-teal

- .github/workflows/master-e2e.yaml
- tests/Makefile
- tests/assets/backup.yaml
- tests/assets/local-kubeconfig-token-skel.yaml
- tests/assets/restore.yaml
- tests/e2e/backup-restore_test.go
- tests/e2e/install_test.go
- tests/e2e/suite_test.go
- tests/e2e/uninstall-operator_test.go
This should fix https://github.com/rancher/elemental-operator/issues/387.
- [OBS-Dev-K3s-E2E](https://github.com/rancher/elemental/actions/runs/4561409676)
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4562663586)
> E2e add backup restore test

- tests/e2e/install_test.go
Just a small code improvement.
- [OBS-Dev-RKE2-E2E](https://github.com/rancher/elemental/actions/runs/4564155775)
- [RKE2-UI_E2E-Stable_RM](https://github.com/rancher/elemental/actions/runs/4565049310) :hourglass_flowing_sand:
> ci/e2e: small fix for CA test

- .github/workflows/qase-test.yaml
Add a new workflow to test https://help.qase.io/en/articles/7210938-github
> ci: add workflow to test Qase triggering

- framework/files/usr/sbin/suc-upgrade
> Do not compare versions from different repositories on upgrades

- .github/workflows/master-e2e.yaml
- tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Will fix upgrade tests using dev operator as well as testing https://github.com/rancher/elemental-operator/pull/437
[UI-K3s-OS-Upgrade-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/4892368550) :heavy_check_mark: 
[UI-K3s-OS-Upgrade-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4892370313) :heavy_check_mark: 
[UI-K3s-Rancher_Latest](https://github.com/rancher/elemental/actions/runs/4893488889) :heavy_check_mark:
> ci/ui: check embedded machineOsVersionChannel
